services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r tg_bot/requirements.txt
    startCommand: python -m tg_bot.bot
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8