services:
  - type: web
    name: telegram-order-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: API_TOKEN
        value: 7915223040:AAHtggDka27CgXPFjl6EVo4cNR0gNPfQ_e0
      - key: OWNER_ID
        value: "5914148670"